// Generated by gencpp from file MainRobot/motor_serialRequest.msg
// DO NOT EDIT!


#ifndef MAINROBOT_MESSAGE_MOTOR_SERIALREQUEST_H
#define MAINROBOT_MESSAGE_MOTOR_SERIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace MainRobot
{
template <class ContainerAllocator>
struct motor_serialRequest_
{
  typedef motor_serialRequest_<ContainerAllocator> Type;

  motor_serialRequest_()
    : id(0)
    , cmd(0)
    , data(0)  {
    }
  motor_serialRequest_(const ContainerAllocator& _alloc)
    : id(0)
    , cmd(0)
    , data(0)  {
  (void)_alloc;
    }



   typedef uint8_t _id_type;
  _id_type id;

   typedef uint8_t _cmd_type;
  _cmd_type cmd;

   typedef int16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::MainRobot::motor_serialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MainRobot::motor_serialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct motor_serialRequest_

typedef ::MainRobot::motor_serialRequest_<std::allocator<void> > motor_serialRequest;

typedef boost::shared_ptr< ::MainRobot::motor_serialRequest > motor_serialRequestPtr;
typedef boost::shared_ptr< ::MainRobot::motor_serialRequest const> motor_serialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::MainRobot::motor_serialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::MainRobot::motor_serialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::MainRobot::motor_serialRequest_<ContainerAllocator1> & lhs, const ::MainRobot::motor_serialRequest_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.cmd == rhs.cmd &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::MainRobot::motor_serialRequest_<ContainerAllocator1> & lhs, const ::MainRobot::motor_serialRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace MainRobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::MainRobot::motor_serialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MainRobot::motor_serialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MainRobot::motor_serialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c12664693d384a430f1b8caa7efe0e71";
  }

  static const char* value(const ::MainRobot::motor_serialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc12664693d384a43ULL;
  static const uint64_t static_value2 = 0x0f1b8caa7efe0e71ULL;
};

template<class ContainerAllocator>
struct DataType< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MainRobot/motor_serialRequest";
  }

  static const char* value(const ::MainRobot::motor_serialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 id\n"
"uint8 cmd\n"
"int16 data\n"
;
  }

  static const char* value(const ::MainRobot::motor_serialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.cmd);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_serialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MainRobot::motor_serialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::MainRobot::motor_serialRequest_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "cmd: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.cmd);
    s << indent << "data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAINROBOT_MESSAGE_MOTOR_SERIALREQUEST_H
