// Generated by gencpp from file MainRobot/motor_serial.msg
// DO NOT EDIT!


#ifndef MAINROBOT_MESSAGE_MOTOR_SERIAL_H
#define MAINROBOT_MESSAGE_MOTOR_SERIAL_H

#include <ros/service_traits.h>


#include <MainRobot/motor_serialRequest.h>
#include <MainRobot/motor_serialResponse.h>


namespace MainRobot
{

struct motor_serial
{

typedef motor_serialRequest Request;
typedef motor_serialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct motor_serial
} // namespace MainRobot


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::MainRobot::motor_serial > {
  static const char* value()
  {
    return "145fd4bef55a3bc00166d50e6ebdc608";
  }

  static const char* value(const ::MainRobot::motor_serial&) { return value(); }
};

template<>
struct DataType< ::MainRobot::motor_serial > {
  static const char* value()
  {
    return "MainRobot/motor_serial";
  }

  static const char* value(const ::MainRobot::motor_serial&) { return value(); }
};


// service_traits::MD5Sum< ::MainRobot::motor_serialRequest> should match
// service_traits::MD5Sum< ::MainRobot::motor_serial >
template<>
struct MD5Sum< ::MainRobot::motor_serialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::MainRobot::motor_serial >::value();
  }
  static const char* value(const ::MainRobot::motor_serialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::MainRobot::motor_serialRequest> should match
// service_traits::DataType< ::MainRobot::motor_serial >
template<>
struct DataType< ::MainRobot::motor_serialRequest>
{
  static const char* value()
  {
    return DataType< ::MainRobot::motor_serial >::value();
  }
  static const char* value(const ::MainRobot::motor_serialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::MainRobot::motor_serialResponse> should match
// service_traits::MD5Sum< ::MainRobot::motor_serial >
template<>
struct MD5Sum< ::MainRobot::motor_serialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::MainRobot::motor_serial >::value();
  }
  static const char* value(const ::MainRobot::motor_serialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::MainRobot::motor_serialResponse> should match
// service_traits::DataType< ::MainRobot::motor_serial >
template<>
struct DataType< ::MainRobot::motor_serialResponse>
{
  static const char* value()
  {
    return DataType< ::MainRobot::motor_serial >::value();
  }
  static const char* value(const ::MainRobot::motor_serialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAINROBOT_MESSAGE_MOTOR_SERIAL_H
