// Generated by gencpp from file MainRobot/motor_serialResponse.msg
// DO NOT EDIT!


#ifndef MAINROBOT_MESSAGE_MOTOR_SERIALRESPONSE_H
#define MAINROBOT_MESSAGE_MOTOR_SERIALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace MainRobot
{
template <class ContainerAllocator>
struct motor_serialResponse_
{
  typedef motor_serialResponse_<ContainerAllocator> Type;

  motor_serialResponse_()
    : data(0)  {
    }
  motor_serialResponse_(const ContainerAllocator& _alloc)
    : data(0)  {
  (void)_alloc;
    }



   typedef int16_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::MainRobot::motor_serialResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::MainRobot::motor_serialResponse_<ContainerAllocator> const> ConstPtr;

}; // struct motor_serialResponse_

typedef ::MainRobot::motor_serialResponse_<std::allocator<void> > motor_serialResponse;

typedef boost::shared_ptr< ::MainRobot::motor_serialResponse > motor_serialResponsePtr;
typedef boost::shared_ptr< ::MainRobot::motor_serialResponse const> motor_serialResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::MainRobot::motor_serialResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::MainRobot::motor_serialResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::MainRobot::motor_serialResponse_<ContainerAllocator1> & lhs, const ::MainRobot::motor_serialResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::MainRobot::motor_serialResponse_<ContainerAllocator1> & lhs, const ::MainRobot::motor_serialResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace MainRobot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::MainRobot::motor_serialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::MainRobot::motor_serialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::MainRobot::motor_serialResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8524586e34fbd7cb1c08c5f5f1ca0e57";
  }

  static const char* value(const ::MainRobot::motor_serialResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8524586e34fbd7cbULL;
  static const uint64_t static_value2 = 0x1c08c5f5f1ca0e57ULL;
};

template<class ContainerAllocator>
struct DataType< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "MainRobot/motor_serialResponse";
  }

  static const char* value(const ::MainRobot::motor_serialResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 data\n"
;
  }

  static const char* value(const ::MainRobot::motor_serialResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_serialResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::MainRobot::motor_serialResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::MainRobot::motor_serialResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<int16_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAINROBOT_MESSAGE_MOTOR_SERIALRESPONSE_H
